# @package _global_

model:

  method: einv2

  loss:
    _target_: loss.einv2.Losses_agg_pit
    loss_fn: mse
    loss_type: loss_all
    loss_alpha: 0.
    method: mACCDOA_pit # mACCDOA_pit | ACCDOA

  thresh_unify: 10 # adpit

  optimizer:
    method: AdamW
    kwargs: {lr: 0.0001, amsgrad: false}