# https://hydra.cc/docs/configure_hydra/intro/

# enable color logging
defaults:
  - override hydra_logging: colorlog
  - override job_logging: colorlog
  - _self_

# output directory, generated dynamically on each run
run:
  dir: ${paths.log_dir}/${task_name}/runs/${experiment_name}
sweep:
  dir: ${paths.log_dir}/${task_name}/multiruns/${experiment_name}
  subdir: ${hydra.job.num}

job_logging:
  handlers:
    file:
      filename: ${hydra.runtime.output_dir}/${hydra.job.name}.log