
batch_size: 256

backbone: CRNN
decoder: gru # gru | conformer | null
num_decoder_layers: 2
kwargs:
  encoder: CNN8
  num_features: [32, 64, 128, 256]
  audioset_pretrain: false
  pretrained_path: null

optimizer:
  method: AdamW
  kwargs: {lr: 0.001, amsgrad: false}

lr_scheduler:
  method: StepLR #CosineAnnealingLR | StepLR
  # kwargs: {milestones: [70, 85], gamma: 0.1} # StepLR
  # kwargs: {T_max: 50, eta_min: 5e-6} # CosineAnnealingLR
  kwargs: {step_size: 40, gamma: 0.1} # StepLR

# num_warmup_steps: 5