
batch_size: 128

backbone: HTSAT
decoder: null # gru | conformer | null
num_decoder_layers: 2
kwargs:
  spec_size: 256
  patch_size: 4
  patch_stride: [4, 4]
  embed_dim: 96
  depths: [2, 2, 6, 2]
  num_heads: [4, 8, 16, 32]
  window_size: 8
  mlp_ratio: 4
  qkv_bias: true
  drop_rate: 0.
  attn_drop_rate: 0.
  drop_path_rate: 0.1
  ape: false
  patch_norm: true
  norm_before_mlp: ln # ln | bn
  audioset_pretrain: true
  pretrained_path: ckpts/HTSAT-fullset-imagenet-768d-32000hz.ckpt

optimizer:
  method: AdamW
  kwargs: {lr: 0.0001, amsgrad: false}

lr_scheduler:
  method: StepLR #CosinseAnnealingLR | StepLR | MultiStepLR
  # kwargs: {milestones: [70, 85], gamma: 0.1} # MultiStepLR
  # kwargs: {T_max: 30, eta_min: 5e-6} # CosineAnnealingLR
  kwargs: {step_size: 40, gamma: 0.1} # StepLR

num_warmup_steps: 5