method: mono_adapter

# Fine-tuning using monophonic clips
# Used in mACCDOA and ACCDOA
adapt_kwargs:
  position: [MlpAdapter,SpatialAdapter] # MlpAdapter or SpatialAdapter
  type: adapter # adapter
  mlp_ratio: 0.5
  act_layer: 'gelu'
  adapter_scalar: 0.1 # learnable_scalar