# specify here default configuration
# order of defaults determines the order in which configs override each other
defaults:
  - hydra: default.yaml
  - logger: tensorboard.yaml # set logger here or use command line (e.g. `python train.py logger=tensorboard`)
  - paths: default.yaml
  - augment: default.yaml
  - data: default.yaml
  - model: htsat.yaml
  - loss: accdoa.yaml
  - extras: default.yaml
  - callbacks: default.yaml
  - trainer: default.yaml
  - task: seld.yaml
  - adapt: default.yaml
  - _self_

  # experiment configs allow for version control of specific hyperparameters
  # e.g. best hyperparameters for given model and datamodule
  - experiment: null

  # debugging config (enable through command line, e.g. `python train.py debug=default)
  - debug: null

# task name, determines output directory path
task_name: ${model.method}_${model.backbone}_infer
experiment_name: ${now:%Y-%m-%d}_${now:%H-%M-%S}

mode: valid # valid | test

num_workers: 8

sed_threshold: 0.5
# sed_threshold: [0.3, 0.5, 0.1, 0.5, 0.5, 0.3, 0.5, 0.5, 0.5, 0.5, 0.3, 0.5, 0.5, 0.3] # 14 classes for L3DAS22
# sed_threshold: [0.5, 0.5, 0.3, 0.3, 0.5, 0.5, 0.5, 0.1, 0.1, 0.3, 0.5, 0.3] # 12 classes for DCASE2021
# sed_threshold: [0.5, 0.5, 0.5, 0.5, 0.1, 0.1, 0.1, 0.5, 0.5, 0.5, 0.1, 0.5, 0.5] # 13 classes for STARSS23

# simply provide checkpoint path to resume training
ckpt_path: null

# seed for random number generators in pytorch, numpy and python.random
seed: 42

# compile model for faster training with pytorch 2.0
compile: false

post_processing: null